name: dart_codecov
version: 0.0.0
description: Send coverage reports to codecov.io. Designed to run on travis-ci.
dependencies:
  args: '>=0.13.0 <0.14.0'
  logging: '>=0.10.0 <0.11.0'
dev_dependencies:
  coverage:
    git:
      url: https://github.com/ekweible/coverage.git
      ref: master
  dart_codecov_generator:
    git:
      url: https://github.com/ekweible/dart_codecov_generator.git
      ref: master
  test: '>=0.12.0 <0.13.0'
dependency_overrides:
  logging: '>=0.10.0 <0.11.0'
executables:
  dart_codecov: